# SwiftLint Configuration for ODYSSEY
# Enforces code quality standards and best practices

opt_in_rules:
  # Code style and organization
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where

  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Custom rule configurations
analyzer_rules:
  - unused_declaration
  - unused_import

# Line length configuration - relaxed for better readability
line_length:
  warning: 200
  error: 300
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

# Function length configuration - relaxed for complex automation logic
function_body_length:
  warning: 200
  error: 300

# Type body length configuration - relaxed for large service classes
type_body_length:
  warning: 2000
  error: 5000

# File length configuration - relaxed for large service files
file_length:
  warning: 2000
  error: 5000

# Identifier length configuration
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - URL
    - x
    - y
    - z

# Force unwrapping configuration
force_unwrapping:
  severity: error

# Implicitly unwrapped optional configuration
implicitly_unwrapped_optional:
  severity: error
  mode: all_except_iboutlets

# Cyclomatic complexity - relaxed for complex automation logic
cyclomatic_complexity:
  warning: 15
  error: 25

# Function parameter count - relaxed for complex automation functions
function_parameter_count:
  warning: 7
  error: 10

# Exclude specific files or rules for acceptable warnings
disabled_rules:
  - multiple_closures_with_trailing_closure # SwiftUI requires this pattern
  - for_where # Sometimes if inside for is more readable
  - orphaned_doc_comment # Some comments are intentionally orphaned
  - unused_optional_binding # Sometimes needed for side effects
  - opening_brace # Style preference, not critical
  - trailing_comma # Style preference, not critical

# Large tuple - relaxed for complex return types
large_tuple:
  warning: 4
  error: 6

# Exclude patterns
excluded:
  - Sources/Resources
  - .build
  - Config/ODYSSEY.xcodeproj
  - Documentation
  - Scripts
  - Sources/Services/WebKitService.swift # Very large file, acceptable
  - Sources/Services/EmailService.swift # Complex email logic, acceptable
  - Sources/Services/ReservationOrchestrator.swift # Complex orchestration logic
  - Sources/Services/ReservationErrorHandler.swift # Complex error handling logic
  - Sources/SharedUtils/JavaScriptLibrary.swift # Large JavaScript library, acceptable
