# SwiftLint Configuration for ODYSSEY
# This file configures SwiftLint to enforce code quality standards

# Disable all rules by default
disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - cyclomatic_complexity
  - large_tuple
  - unused_import
  - unused_private_declaration
  - trailing_newline
  - identifier_name
  - multiple_closures_with_trailing_closure
  - unused_closure_parameter
  - unused_enumerated
  - for_where

# Enable specific rules
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - static_operator
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rule configurations
analyzer_rules:
  - unused_declaration
  - unused_import

# Custom rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

large_tuple:
  warning: 3
  error: 4

# Exclude patterns
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - "*.generated.swift"

# Custom rules
custom_rules:
  odyssey_logging:
    name: "ODYSSEY Logging"
    regex: "print\\(|NSLog\\("
    message: "Use os.log Logger instead of print or NSLog"
    severity: warning
