---
name: ODYSSEY
options:
  bundleIdPrefix: com.odyssey
  deploymentTarget:
    macOS: "26"
  xcodeVersion: "26"
  groupSortPosition: top
  generateEmptyDirectories: true
  fileTypes:
    swift: sourcecode.swift
    plist: text.plist.xml
settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: ""
    SWIFT_VERSION: 6.2
    SUPPORTED_PLATFORMS: macosx
    SDKROOT: macosx
    ENABLE_PREVIEWS: YES
    MACOSX_DEPLOYMENT_TARGET: 26
    PRODUCT_BUNDLE_IDENTIFIER: com.odyssey.app
    PRODUCT_NAME: ODYSSEY
    MARKETING_VERSION: ${MARKETING_VERSION}
    CURRENT_PROJECT_VERSION: 1
    INFOPLIST_FILE: ../Sources/AppCore/Info.plist
    INFOPLIST_KEY_CFBundleDisplayName: ODYSSEY
    INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
    INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2025 Amet13. All rights reserved."
    INFOPLIST_KEY_LSUIElement: true
    INFOPLIST_KEY_NSAppTransportSecurity_NSAllowsArbitraryLoads: false
    ENABLE_HARDENED_RUNTIME: YES
    ENABLE_APP_SANDBOX: YES
    SWIFT_OPTIMIZATION_LEVEL: -Onone
    GCC_OPTIMIZATION_LEVEL: 0
    DEBUG_INFORMATION_FORMAT: dwarf
    ENABLE_STRICT_OBJC_MSGSEND: YES
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
    CLANG_WARN_DOCUMENTATION_COMMENTS: YES
    CLANG_WARN_EMPTY_BODY: YES
    CLANG_WARN_ENUM_CONVERSION: YES
    CLANG_WARN_INFINITE_RECURSION: YES
    CLANG_WARN_INT_CONVERSION: YES
    CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
    CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
    CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
    CLANG_WARN_STRICT_PROTOTYPES: YES
    CLANG_WARN_SUSPICIOUS_IMPLICIT_CONVERSION: YES
    CLANG_WARN_UNGUARDED_AVAILABILITY: YES
    CLANG_WARN_UNREACHABLE_CODE: YES
    CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
    SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
    GCC_TREAT_WARNINGS_AS_ERRORS: YES
    # Additional quality settings
    SWIFT_SUPPRESS_WARNINGS: NO
    GCC_WARN_64_TO_32_BIT_CONVERSION: YES
    GCC_WARN_ABOUT_RETURN_TYPE: YES
    GCC_WARN_UNINITIALIZED_AUTOS: YES
    GCC_WARN_UNUSED_FUNCTION: YES
    GCC_WARN_UNUSED_VARIABLE: YES
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      GCC_OPTIMIZATION_LEVEL: 0
      DEBUG_INFORMATION_FORMAT: dwarf
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      GCC_PREPROCESSOR_DEFINITIONS: DEBUG=1
      SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
    Release:
      SWIFT_OPTIMIZATION_LEVEL: -O
      GCC_OPTIMIZATION_LEVEL: s
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      GCC_PREPROCESSOR_DEFINITIONS: NDEBUG=1
      SWIFT_TREAT_WARNINGS_AS_ERRORS: YES
targets:
  ODYSSEY:
    type: application
    platform: macOS
    definesModule: true
    path: ../Sources
    sources:
      - path: ../Sources
        excludes:
          - "**/*.md"
          - "**/*.txt"
          - "**/*.xcuserstate"
          - "**/*.xcuserdata"
          - "**/*.xcworkspace"
          - "**/*.xcodeproj"
          - "Application/**"
          - "Domain/**"
          - "Infrastructure/**"
          - "Presentation/**"
          - "SharedCore/**"
    resources:
      - path: ../Sources/Resources/AppIcon.icns
      - path: ../Sources/Resources/Assets.xcassets
      - path: ../Sources/Resources/Localizable.strings

    info:
      path: ../Sources/AppCore/Info.plist
      properties:
        CFBundleName: "ODYSSEY"
        CFBundleIdentifier: "com.odyssey.app"
        CFBundleShortVersionString: 3.1.2
        CFBundleVersion: "1"
        CFBundleDisplayName: "ODYSSEY"
        CFBundlePackageType: "APPL"
        CFBundleSignature: "????"
        CFBundleExecutable: "ODYSSEY"
        CFBundleIconFile: "AppIcon.icns"
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleDevelopmentRegion: "en"
        LSApplicationCategoryType: public.app-category.utilities
        LSUIElement: true
        NSHumanReadableCopyright: "Copyright © 2025 Amet13. All rights reserved."
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSExceptionDomains:
            reservation.frontdesksuite.ca:
              NSExceptionAllowsInsecureHTTPLoads: false
              NSIncludesSubdomains: true
              NSRequiresCertificateTransparency: false
        CFBundleIconName: "AppIcon"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.odyssey.app"
        PRODUCT_NAME: "ODYSSEY"
        MARKETING_VERSION: ${MARKETING_VERSION}
        CURRENT_PROJECT_VERSION: 11
        INFOPLIST_FILE: ../Sources/AppCore/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: "ODYSSEY"
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2025 Amet13. All rights reserved."
        INFOPLIST_KEY_LSUIElement: true
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_APP_SANDBOX: YES
        SWIFT_VERSION: 6.2
        MACOSX_DEPLOYMENT_TARGET: 26
        ENABLE_PREVIEWS: YES
        SUPPORTED_PLATFORMS: macosx
        SDKROOT: macosx
    dependencies: []

    postCompileBuildScripts:
      - name: "Code Signing Check"
        script: |
          echo "Checking code signing status..."
          codesign -dv "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app" 2>&1 || echo "App not code signed"
        inputFiles: []
        outputFiles: []
        shell: /bin/bash
        runOnlyForDeploymentPostprocessing: false
        showEnvVarsInLog: false
      - name: "App Size Report"
        script: |
          if [ -d "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app" ]; then
            echo "App size: $(du -sh "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app" | cut -f1)"
          fi
        inputFiles: []
        outputFiles: []
        shell: /bin/bash
        runOnlyForDeploymentPostprocessing: false
        showEnvVarsInLog: false

schemes:
  ODYSSEY:
    shared: true
    build:
      targets:
        ODYSSEY: all
    run:
      config: Debug
    archive:
      config: Release
    profile:
      config: Release
    analyze:
      config: Debug
