name: Nightly Build

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  nightly-build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "latest-stable"

      - name: Install dependencies
        run: |
          brew install xcodegen
          brew install swiftlint

      - name: Generate Xcode project
        run: |
          xcodegen

      - name: Run SwiftLint
        run: |
          swiftlint lint --reporter github-actions-logging

      - name: Build Debug
        run: |
          xcodebuild build \
            -project ORRMAT.xcodeproj \
            -scheme ORRMAT \
            -configuration Debug \
            -destination 'platform=macOS' \
            -quiet

      - name: Build Release
        run: |
          xcodebuild build \
            -project ORRMAT.xcodeproj \
            -scheme ORRMAT \
            -configuration Release \
            -destination 'platform=macOS' \
            -quiet

      - name: Check app sizes
        run: |
          DEBUG_APP=$(find ~/Library/Developer/Xcode/DerivedData -name "ORRMAT.app" -type d 2>/dev/null | grep Debug | head -1)
          RELEASE_APP=$(find ~/Library/Developer/Xcode/DerivedData -name "ORRMAT.app" -type d 2>/dev/null | grep Release | head -1)

          if [ -n "$DEBUG_APP" ]; then
            DEBUG_SIZE=$(du -sh "$DEBUG_APP" | cut -f1)
            echo "Debug app size: $DEBUG_SIZE"
          fi

          if [ -n "$RELEASE_APP" ]; then
            RELEASE_SIZE=$(du -sh "$RELEASE_APP" | cut -f1)
            echo "Release app size: $RELEASE_SIZE"
          fi

          echo "Both builds completed successfully!"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nightly-build-${{ github.run_number }}
          path: |
            ~/Library/Developer/Xcode/DerivedData/ORRMAT-*/Build/Products/Debug/ORRMAT.app
            ~/Library/Developer/Xcode/DerivedData/ORRMAT-*/Build/Products/Release/ORRMAT.app
          retention-days: 7
