---
name: Scheduled Reservation

on:
  schedule:
    - cron: "53 21 * * *" # 21:53 UTC (5:53pm EST)
  workflow_dispatch: # Allow manual runs

jobs:
  run-reservations:
    runs-on: macos-15
    name: Execute Scheduled Reservations

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download ODYSSEY CLI
        run: |
          curl -Ls -o odyssey-cli https://github.com/Amet13/ODYSSEY/releases/latest/download/odyssey-cli
          chmod +x odyssey-cli
          sudo xattr -rd com.apple.quarantine ./odyssey-cli

      - name: Run Reservations
        run: |
          echo "🚀 Starting ODYSSEY reservation automation..."
          ./odyssey-cli run
        env:
          ODYSSEY_EXPORT_TOKEN: ${{ secrets.ODYSSEY_EXPORT_TOKEN }}
