---
name: Scheduled Reservation

on:
  schedule:
    - cron: "53 21 * * *" # 21:53 UTC (5:53pm EST)
  workflow_dispatch: # Allow manual runs

jobs:
  run-reservations:
    runs-on: macos-15
    name: Execute Scheduled Reservations
    timeout-minutes: 10
    env:
      TZ: America/Toronto

    steps:
      - name: Set timezone to Toronto
        run: |
          sudo systemsetup -settimezone "America/Toronto"
          echo "System timezone set to Toronto: $(date)"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download ODYSSEY CLI
        run: |
          curl -Ls -o odyssey-cli https://github.com/Amet13/ODYSSEY/releases/latest/download/odyssey-cli
          chmod +x odyssey-cli
          sudo xattr -rd com.apple.quarantine ./odyssey-cli

      - name: Run Reservations
        run: |
          echo "🚀 Starting ODYSSEY reservation automation..."
          ./odyssey-cli run --hide --screenshots
        env:
          ODYSSEY_EXPORT_TOKEN: ${{ secrets.ODYSSEY_EXPORT_TOKEN }}

      - name: Upload screenshots as artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failure-screenshots
          path: screenshots/
          retention-days: 30
