---
name: Scheduled Reservation

on:
  # schedule:
  #   - cron: "53 21 * * *" # 21:53 UTC (5:53pm EST)
  workflow_dispatch: # Allow manual runs

permissions:
  contents: read

jobs:
  run-reservations:
    runs-on: macos-15
    timeout-minutes: 10
    env:
      TZ: America/Toronto

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download ODYSSEY CLI
        run: |
          curl -Ls -o odyssey-cli https://github.com/Amet13/ODYSSEY/releases/latest/download/odyssey-cli
          chmod +x odyssey-cli
          sudo xattr -rd com.apple.quarantine ./odyssey-cli

      - name: Run Reservations
        run: |
          echo "🚀 Starting ODYSSEY reservation automation..."
          ./odyssey-cli run --hide --screenshots
        env:
          ODYSSEY_EXPORT_TOKEN: ${{ secrets.ODYSSEY_EXPORT_TOKEN }}

      - name: Check for screenshots
        if: always()
        id: screenshots
        run: |
          SCREENSHOT_DIR="$HOME/Library/Application Support/ODYSSEY/Screenshots"
          if [ -d "$SCREENSHOT_DIR" ] && [ "$(ls -A "$SCREENSHOT_DIR" 2>/dev/null)" ]; then
            echo "📸 Screenshots found, will upload artifacts"
            echo "screenshots_exist=true" >> "$GITHUB_OUTPUT"
            echo "screenshot_path=$SCREENSHOT_DIR" >> "$GITHUB_OUTPUT"
          else
            echo "📸 No screenshots found, skipping artifact upload"
            echo "screenshots_exist=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload screenshots as artifacts
        if: always() && steps.screenshots.outputs.screenshots_exist == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: failure-screenshots
          path: ${{ steps.screenshots.outputs.screenshot_path }}/
          retention-days: 30

      - name: Skip screenshot upload
        if: always() && steps.screenshots.outputs.screenshots_exist == 'false'
        run: |
          echo "📸 No screenshots to upload - this is normal when reservations succeed"
